#ifndef OB_TABLES_H
#define OB_TABLES_H

// Catalog records for troops, spells, classes, villains, artifacts. The
// actual data lives in assets/<game>/game.json and is loaded by
// resources_load(); this header only declares the struct layouts and the
// lookup functions. Lookups return NULL before resources_load() has run.

#include <stdbool.h>

#define CAT_ID_LEN    32
#define CAT_NAME_LEN  48
#define CAT_TEXT_LEN 160
#define CAT_PATH_LEN 128

// Caps enforce fixed-size storage so the catalogs stay POD.
#define CAT_TROOPS_MAX              32
#define CAT_SPELLS_MAX              32
#define CAT_CLASSES_MAX              8
#define CAT_VILLAINS_MAX            32
#define CAT_ARTIFACTS_MAX           16
#define CLASS_MAX_RANKS              4
#define CLASS_MAX_STARTING_TROOPS    2

// ----- Troops ---------------------------------------------------------------
typedef enum {
    TROOP_ABIL_NONE   = 0,
    TROOP_ABIL_FLY    = 1 << 0,
    TROOP_ABIL_REGEN  = 1 << 1,
    TROOP_ABIL_MAGIC  = 1 << 2,
    TROOP_ABIL_IMMUNE = 1 << 3,
    TROOP_ABIL_ABSORB = 1 << 4,
    TROOP_ABIL_LEECH  = 1 << 5,
    TROOP_ABIL_SCYTHE = 1 << 6,
    TROOP_ABIL_UNDEAD = 1 << 7,
} TroopAbility;

typedef struct {
    int  index;
    char id[CAT_ID_LEN];
    char name[CAT_NAME_LEN];
    char sprite[CAT_PATH_LEN];
    char anim[4][CAT_PATH_LEN];     // 4-frame idle animation (used by army view + combat)
    int  skill_level;
    int  hit_points;
    int  move_rate;
    int  melee_min, melee_max;
    int  ranged_min, ranged_max, ranged_ammo;
    int  recruit_cost;
    int  spoils_factor;
    int  abilities;
    char dwelling[CAT_ID_LEN];
    int  max_population;
    int  growth_per_week;
    char morale_group;              // 'A'..'E'
    // Monster-stack count generated by repopulate_castle / repopulate_foe,
    // one entry per spawn tier (0=plains, 1=forest, 2=hill, 3=dungeon).
    //  troop_numbers[MAX_TROOPS][MAX_TROOP_DIFFICULTY].
    int  tier_counts[4];
} TroopDef;

const TroopDef *troop_by_id(const char *id);
const TroopDef *troop_by_index(int idx);
int             troops_count(void);

// ----- Spells ---------------------------------------------------------------
typedef enum {
    SPELL_KIND_COMBAT,
    SPELL_KIND_ADVENTURE,
} SpellKind;

typedef struct {
    int       index;
    char      id[CAT_ID_LEN];
    char      name[CAT_NAME_LEN];
    SpellKind kind;
    int       cost;
    char      description[CAT_TEXT_LEN];
} SpellDef;

const SpellDef *spell_by_id(const char *id);
const SpellDef *spell_by_index(int idx);
int             spells_count(void);

// Resolve a spell id to its slot in Game.spells.counts[]. Returns -1 if the
// id is not present in the loaded catalog. Use this instead of hardcoding
// indices like spells.counts[8] for time_stop — slots are decided by the
// order spells appear in game.json and are not part of the engine's API.
int             spell_index_by_id(const char *id);

// ----- Classes + ranks ------------------------------------------------------
typedef struct {
    char id[CAT_ID_LEN];
    char name[CAT_NAME_LEN];
    int  villains_needed;
    int  leadership;
    int  max_spells;
    int  spell_power;
    int  commission;
    bool knows_magic;
    int  instant_army;
} RankDef;

typedef struct {
    int  index;
    char id[CAT_ID_LEN];
    char name[CAT_NAME_LEN];
    char portrait[CAT_PATH_LEN];
    int  starting_gold;
    char starting_troops[CLASS_MAX_STARTING_TROOPS][CAT_ID_LEN];
    int  starting_counts[CLASS_MAX_STARTING_TROOPS];
    int  rank_count;
    RankDef ranks[CLASS_MAX_RANKS];
} ClassDef;

const ClassDef *class_by_id(const char *id);
const ClassDef *class_by_index(int idx);
int             classes_count(void);

// Sum up to rank_index inclusive (rank 0 is absolute, later ranks are deltas).
void class_stats_at_rank(const ClassDef *c, int rank_index,
                         int *leadership, int *max_spells,
                         int *spell_power, int *commission);

// ----- Villains -------------------------------------------------------------
typedef struct {
    int  index;
    char id[CAT_ID_LEN];
    char name[CAT_NAME_LEN];
    char portrait[CAT_PATH_LEN];
    char zone[CAT_ID_LEN];          // home zone id (was "home_continent")
    int  reward;
    int  puzzle_cell;
    // Villain's castle garrison when they're the castle's ruler.
    // Troop ids are catalog ids (not indices). Empty id = unused slot.
    char army_troops[5][CAT_ID_LEN];
    int  army_counts[5];
} VillainDef;

const VillainDef *villain_by_id(const char *id);
const VillainDef *villain_by_index(int idx);
int               villains_count(void);

// ----- Artifacts ------------------------------------------------------------
typedef enum {
    ARTIFACT_POWER_UNKNOWN = 0,     // default when JSON string is missing
    ARTIFACT_POWER_INCREASED_DAMAGE,
    ARTIFACT_POWER_QUARTER_PROTECTION,
    ARTIFACT_POWER_DOUBLE_LEADERSHIP,
    ARTIFACT_POWER_INCREASE_COMMISSION,
    ARTIFACT_POWER_DOUBLE_SPELL_POWER,
    ARTIFACT_POWER_DOUBLE_MAX_SPELLS,
    ARTIFACT_POWER_CHEAPER_BOATS,
} ArtifactPower;

typedef struct {
    int           index;
    char          id[CAT_ID_LEN];
    char          name[CAT_NAME_LEN];
    char          icon[CAT_PATH_LEN];
    ArtifactPower power;
    char          effect[CAT_TEXT_LEN];
    int           puzzle_cell;
    // Placement: which zone holds this artifact and which local slot (0 or 1).
    char          zone[CAT_ID_LEN];
    int           local_idx;
} ArtifactDef;

const ArtifactDef *artifact_by_id(const char *id);
const ArtifactDef *artifact_by_index(int idx);
int                artifacts_count(void);

// Resolve which artifact sits at a given (zone, local_idx) tile slot.
// Returns the artifact index, or -1 if no match.
int artifact_index_for_tile(const char *zone, int local_idx);

// ----- Morale ---------------------------------------------------------------
// morale_chart[my_group][their_group] -> 'N'ormal / 'L'ow / 'H'igh
// my_group and their_group are 'A'..'E' mapped to 0..4.
char morale_result(char my_group, char their_group);

#endif
